name: Change Shell
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        steps:
            - shell: bash
              run: echo "${SHELL}"    # 셸에 bash를 지정
            - shell: python
              run: |
                import os  
                print(os.environ['PATH'])